name: install nginx
on:
  push:
    branches:
      - master
    
jobs:
  check-nginx-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nginxinc/nginx-for-azure-deploy-action@v0.1.0
        with:
          nginx-version: '1.21.6'

      - run: apt install nginx -y

      - run: nginx --version
