name: install nginx
on:
  push:
    branches:
      - master
    
jobs:
  check-nginx-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          nginx-version: '3.10'

      - run: python3 install pip 

      - run: python -v
